### ISSUE TITLE
Writing Application Support to wrong path

### ISSUE THREAD

**Issue by brightghost** [jigish/slate#190] opened 2012-12-23 06:19 UTC
I've found that Slate has been creating a directory called  "file/" (with the trailing slash) in my root directory, and populating it with the directory tree "/file:/localhost/Users/[username]/Library/Application%20Support/com.slate.Slate/" . These directories are being recreated every time slate is relaunched, though it doesn't seem to actually be writing any files in them. Obviously there's a screwy pathname somewhere.

**Comment by josh-** [comment] 2012-12-27 10:28
I think I've found the cause, are you running slate on 10.6?

**Comment by brightghost** [comment] 2012-12-27 16:34
Yep 10.6.8

**Comment by jigish** [comment] 2012-12-28 06:53
Yah thats probably it. As I mentioned on the pull request I'll take a look at it and probably release a fix around jan 6th when I get back from vacation.

**Comment by josh-** [comment] 2012-12-28 08:57
@brightghost Would you be happy to test this patch?

**Comment by brightghost** [comment] 2012-12-28 19:07
I would, but this 10.6.8 system is the only setup I have, so it doesn't look like I'll be able to compile the package due to the use of ARC. Happy to confirm the fix if someone puts together a new build, though.

**Comment by josh-** [comment] 2012-12-28 20:49
@brightghost Okay fantastic, I've just whipped up a build - http://cl.ly/Lq84

**Comment by brightghost** [comment] 2012-12-28 23:56
That seems to have done the trick, thanks josh—

**Comment by josh-** [comment] 2012-12-30 00:29
No worries, thanks for testing it.

**Comment by jigish** [comment] 2013-01-20 00:14
just merged the pull request. will post a new build today.

**Closed as completed by jigish** 2013-01-20 00:14 UTC
Labels: Bug
