### ISSUE TITLE
screen.rect() dimensions aren't offset for Dock and Menubar

### ISSUE THREAD

**Issue by Westacular** [jigish/slate#219] opened 2013-01-29 23:35 UTC
Whereas screenOriginX and Y take into account the size and position of the Dock and the Menubar, screen.rect().x and .y do not.

Similarly, screen.rect().height and .width report the full dimensions of the screen, not the available dimensions after subtracting the area occupied by the Dock and Menubar.

Is this intentional/working as designed? If so, would it be possible to add some other way to check access the Dock/Menu-adjusted values?

**Comment by jigish** [comment] 2013-01-30 00:16
so this is working as intended so that you can get the actual resolution of the screen.

you make a good point, though. I'll add a `screen.visibleRect()` method to get the visible dimensions of the screen. That will take into account Dock and Menubar.

**Comment by jigish** [comment] 2013-01-30 01:35
added. will be in the next version.

**Closed as completed by jigish** 2013-01-30 01:35 UTC
Labels: Improvement

**Comment by Westacular** [comment] 2013-01-30 05:35
Wonderful! Thanks a lot.
